### ISSUE TITLE
Question: is there 1wire support ?

### ISSUE THREAD

**Issue by ccmsi** [MrYsLab/FirmataExpress#10]
I'm confused whether this supports 1wire protool or not. I do not find such a hint into the ocumentation, however i did find support for a DHT22 tempreature sensor which supposedly does use 1wire protocol.

Please clarify. Thanks for this the work you're providing.

**Comment by MrYsLab** [comment]
The One Wire Protocol is for devices manufactured by [Maxim](https://www.maximintegrated.com/en.html), and StandardFirmata, which FirmataExpress is based does not support that protocol, and therefore neither does FirmataExpress. The DHT22 uses a different protocol that is not One Wire (although there is a single data pin connection).

I have tried integrating One Wire into FirmataExpress in the past and simply could not get it to work, so sadly, there is no One Wire support.
