### ISSUE TITLE
Error compiling for board Arduino Uno.

### ISSUE THREAD

**Issue by tarlan-1907** [MrYsLab/FirmataExpress#17]

**Comment by MrYsLab** [comment]
Please provide a screen dump of the error.

**Comment by tarlan-1907** [comment]
![Screenshot 2022-05-07 192515](https://user-images.githubusercontent.com/81584399/167260874-3db53abe-6cf6-4b21-9ab7-3c663318913f.png)

**Comment by MrYsLab** [comment]
I compiled version 1.2.0 using Arduino IDE 1.8.19 and am only getting a warning that can be ignored.
Make sure that you are using 1.2.0 and try upgrading to 1.8.19 of the IDE.

If you are still having issues, please copy and paste all of the errors/warnings shown in the bottom half of the IDE.

I am going to move this issue over to FirmataExpress
![Screenshot from 2022-05-07 11-32-31](https://user-images.githubusercontent.com/5189838/167261703-9d469cb0-f7b7-4c6f-a69d-f1365b0772ad.png)
.

**Comment by MrYsLab** [comment]
I am closing this issue; however, if you are still having problems, please post the error output here, and I will reopen the issue if necessary.
