### ISSUE TITLE
Ultrasonic:No such file or directory

### ISSUE THREAD

**Issue by HotView** [MrYsLab/FirmataExpress#3]
cant find the Ultrasonic.h file.
help thanks

**Comment by MrYsLab** [comment]
Hi,
Please take a look at [this section](https://mryslab.github.io/pymata-express/firmata_express/) in the installation instructions in the pymata-express documentation. 
Please let me know if that helps.

**Comment by HotView** [comment]
A very helpful answer，thanks.
