### ISSUE TITLE
where can I download ultrasonic library

### ISSUE THREAD

**Issue by ouki-wang** [MrYsLab/FirmataExpress#5]
I compiled FirmataExpress librariy and found that：

Alternatives for Ultrasonic.h: []
FirmataExpress:38:10: fatal error: Ultrasonic.h: No such file or directory
ResolveLibrary(Ultrasonic.h)

so，where can I download ultrasonic library？

**Comment by MrYsLab** [comment]
If you look at item 4 [on this page](https://mryslab.github.io/pymata-express/firmata_express/), it provides installation instructions.
