### ISSUE TITLE
Robo HAT MM1 / Firmata Express Firmware - no Ultrasonic.h

### ISSUE THREAD

**Issue by wallarug** [MrYsLab/FirmataExpress#9]
Hi @MrYsLab ,

Trying to compile the FirmataExpress for Robo HAT MM1 and hit an issue.

```
FirmataExpress:41:10: fatal error: Ultrasonic.h: No such file or directory

 #include <Ultrasonic.h>

          ^~~~~~~~~~~~~~

compilation terminated.

exit status 1
Ultrasonic.h: No such file or directory
```

**Comment by wallarug** [comment]
I presume it is this library missing: https://github.com/ErickSimoes/Ultrasonic

Might need to either include it in the release or at least say it is a dependency with instructions on how to install it.

**Comment by MrYsLab** [comment]
This is documented here https://mryslab.github.io/pymata_rh/firmata_express/.
Item #4 addresses this.

**Comment by wallarug** [comment]
Ahh, I see this now.  Thank you!

**Comment by MrYsLab** [comment]
It looks like the Arduino IDE now will accept dependencies and will suggest installing them when installing the host library.
I will update Firmata-Express to take advantage of this relatively new feature. I will be working on a problem reported for the STM32 and am waiting for an STM32 board to arrive. If any changes are required for the STM32, I will incorporate the dependency then. If no changes are necessary, I will generate a new release with the dependency. Long story short, it will probably be about a week before I incorporate the dependency change.

**Comment by MrYsLab** [comment]
The Arduino now prompts the user to install Ultrasonic.

**Comment by wallarug** [comment]
Thanks Alan!
